http://localhost:3003/api/v1/users

###

http://localhost:3003/api/v1/users/lyman93

###
POST http://localhost:3003/api/v1/users/lyman93
CONTENT-TYPE: application/json

{
  "userName": "lyman93",
  "password": "password",
  "email": "email@email.com",
  "isAdmin": true,
  "profilePicture": "./images/profilePicture.jpg"
}

###
POST http://localhost:3003/api/v1/users/authenticate
CONTENT-TYPE: application/json

{
  "userName": "lyman93",
  "password": "password"
}

###

DELETE http://localhost:3003/api/v1/users/lyman

###

POST http://localhost:3003/api/v1/workouts/add-workout
CONTENT-TYPE: application/json

{
  "userName": "lyman93",
  "trainingType": "strength",
  "exerciseQuantity": 2,
  "date": "2022-12-04T05:00:00.000Z"
}

###
POST http://localhost:3003/api/v1/workouts/date-workouts
CONTENT-TYPE: application/json

{
  "userName": "lyman93",
  "date": "2022-12-04T05:00:00.000Z"
}