http://localhost:3003/api/v1/users

###
http://localhost:3003/api/v1/users/lyman93

###
http://localhost:3003/api/v1/users/search/a

###
POST http://localhost:3003/api/v1/users/authenticate
CONTENT-TYPE: application/json

{
  "userName": "lyman93",
  "password": "password"
}

###
POST http://localhost:3003/api/v1/users/create-user
CONTENT-TYPE: application/json

{
  "userName": "newUser",
  "password": "password",
  "email": "newuser1@gmail.com"
}

###
POST http://localhost:3003/api/v1/users/create-admin
CONTENT-TYPE: application/json

{
  "userName": "lyman93",
  "password": "password",
  "email": "lyman93@gmail.com"
}

###
PATCH http://localhost:3003/api/v1/users/edit-profile
CONTENT-TYPE: application/json

{
  "userName": "admin",
  "newUserName": "amine",
  "newEmail": "amine@gmail.com"
}

###
Delete http://localhost:3003/api/v1/users/newUser

###
PATCH http://localhost:3003/api/v1/users/send-friend-request
CONTENT-TYPE: application/json

{
  "senderName": "abc",
  "friendName": "lyman93"
}

###
http://localhost:3003/api/v1/users/lyman93/friends