POST http://localhost:3003/api/v1/workouts/add-workout
CONTENT-TYPE: application/json

{
  "userName": "lyman93",
  "trainingType": "bodybuilding",
  "exerciseQuantity": 2,
  "date": "2022-12-07T05:00:00.000Z"
}

###
POST http://localhost:3003/api/v1/workouts/date-workouts
CONTENT-TYPE: application/json

{
  "userName": "lyman93",
  "date": "2022-12-07T05:00:00.000Z"
}

###
http://localhost:3003/api/v1/workouts/lyman

###
http://localhost:3003/api/v1/workouts/social/lyman93